/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GoodCard: typeof import('./src/components/home/GoodCard.vue')['default']
    Item: typeof import('./src/components/message/item.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialCard: typeof import('./src/components/community/SocialCard.vue')['default']
  }
}
